# Generated by Django 6.0.6 on 2026-06-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_team_flag_image'),
        ('pool', '0016_poolscoringconfig_knockout_draw_prediction_points'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolRankingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_index', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('total_points', models.IntegerField(default=0)),
                ('group_points', models.IntegerField(default=0)),
                ('knockout_points', models.IntegerField(default=0)),
                ('exact_score_hits', models.IntegerField(default=0)),
                ('advancing_hits', models.IntegerField(default=0)),
                ('champion_hit', models.BooleanField(default=False)),
                ('top_scorer_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to='football.match')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to='pool.poolparticipant')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to='pool.pool')),
            ],
            options={
                'ordering': ['pool', 'round_index', 'position'],
                'indexes': [models.Index(fields=['pool', 'round_index'], name='pool_rank_hist_round_idx')],
                'unique_together': {('pool', 'participant', 'match')},
            },
        ),
    ]
