# Generated by Django 6.0.4 on 2026-06-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_team_flag_image'),
        ('rankings', '0002_poolrankinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolRankingSnapshotJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('IDLE', 'Idle')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_snapshot_job', to='football.match')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
