# Generated by Django 6.0.4 on 2026-06-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0016_poolscoringconfig_knockout_draw_prediction_points'),
        ('rankings', '0003_poolrankingsnapshotjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolDashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshot', to='pool.pool')),
            ],
        ),
        migrations.CreateModel(
            name='PoolDashboardSnapshotJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('IDLE', 'Idle')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_snapshot_job', to='pool.pool')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
