exclude: |
  (?x)^(
      .*\{\{.*\}\}.*|     # Exclude any files with cookiecutter variables
      docs/site/.*|       # Exclude mkdocs compiled files
      \.history/.*|       # Exclude history files
      .*cache.*/.*|       # Exclude cache directories
      .*venv.*/.*|        # Exclude virtual environment directories
  )$
fail_fast: true
default_language_version:
  python: python3.12
default_install_hook_types:
  - pre-commit
repos:
  #
  # Documentation Here:
  # https://gatlenculp.github.io/gatlens-opinionated-template/precommit/
  #
  # ---------------------------------------------------------------------------- #
  #                              🔄 Pre-Commit Hooks                             #
  # ---------------------------------------------------------------------------- #

  # ----------------------------- 🔒 Security Tools ---------------------------- #

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.1
    hooks:
      - id: gitleaks
        name: "🔒 security · Detect hardcoded secrets"

  # --------------------------- 🔍 Code Quality Tools -------------------------- #

  ### Python Tools ###
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.13
    hooks:
      # Run the linter.
      - id: ruff-check
        name: "🐍 python · Lint with Ruff"
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        name: "🐍 python · Format with Ruff"

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject
        name: "🐍 python · Validate pyproject.toml"
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  ### Javascript & Web Tools ###
  #   - repo: https://github.com/biomejs/pre-commit
  #     rev: "v0.6.1"
  #     hooks:
  #       - id: biome-check
  #         name: "🟨 javascript · Lint, format, and safe fixes with Biome"
  #         additional_dependencies: ["@biomejs/biome@1.9.4"]

  ### Data & Config Validation ###
  #   - repo: https://github.com/python-jsonschema/check-jsonschema
  #     rev: 0.31.0
  #     hooks:
  #       - id: check-github-workflows
  #         name: "🐙 github-actions · Validate gh workflow files"
  #         args: ["--verbose"]
  #       - id: check-taskfile
  #         name: "✅ taskfile · Validate Task configuration"

  ### Markdown ###
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.21
    hooks:
      - id: mdformat
        name: "📝 markdown · Format markdown"
        additional_dependencies:
          - mdformat-gfm
          - mdformat-ruff
          - mdformat-frontmatter
          - ruff

  ### Additional File Types ###
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: "✨ misc-files · Format YAML/SCSS"
        types_or: [yaml, scss]
        exclude: ^src/matches/templates/matches/match_list\.html$
        additional_dependencies:
          - prettier@3.4.2

  # ---------------------------- 📁 Filesystem Tools --------------------------- #

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Filesystem Checks
      - id: trailing-whitespace
        name: "📁 filesystem/📝 whitespace · Remove trailing whitespace"
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        name: "📁 filesystem/📝 eof · Ensure newline at end of file"
      - id: check-yaml
        name: "📁 filesystem/📝 names · Check YAML files"
      - id: check-illegal-windows-names
        name: "📁 filesystem/📝 names · Validate Windows filenames"
      - id: debug-statements
        name: "📁 filesystem/🐍 debug · Detect debug statements in Python"
      # ------------------------------- 🌳 Git Tools ------------------------------- #
      - id: check-merge-conflict
        name: "🌳 git · Detect conflict markers"
      - id: check-added-large-files
        name: "🌳 git · Block large file commits"
        args: ["--maxkb=5000"]

  # ---------------------------------------------------------------------------- #
  #                             🧪 Fast Tests (Local)                            #
  # ---------------------------------------------------------------------------- #
#   - repo: local
#     hooks:
#       - id: pytest-collect
#         name: 🧪 test · Validate test formatting
#         entry: ./.venv/bin/pytest tests
#         language: system
#         types: [python]
#         args: ["--collect-only"]
#         pass_filenames: false
#         always_run: true
#       # STRICT
#       - id: pytest-fast
#         name: 🧪 test · Run fast tests
#         entry: ./.venv/bin/pytest tests
#         language: system
#         types: [python]
#         args: ["--max-timeout=3"]
#         pass_filenames: false
#         always_run: true
