services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: penninicup
      POSTGRES_USER: penninicup
      POSTGRES_PASSWORD: penninicup
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
      PENNINIBET_DATABASES: '{"default":{"HOST":"db"}}'
      PENNINIBET_LOCAL_SETTINGS_PATH: "local/settings.prod.py"

volumes:
  postgresql-data:
    driver: local
