# Generated by Django 6.0.1 on 2026-04-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_amount_alter_payment_amount_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mercadopago', max_length=32)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
