# Generated by Django 6.0.1 on 2026-03-18 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='sync_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='sync_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='sync_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='sync_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='sync_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
