# Generated by Django 6.0.1 on 2026-03-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_group_create_date_group_sync_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='fifa_id',
            field=models.CharField(default=121232134, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
