# Generated by Django 6.0.1 on 2026-03-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_stage_fifa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
