# Generated by Django 6.0.1 on 2026-03-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_stadium_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
