# Generated by Django 6.0.1 on 2026-03-21 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_alter_stadium_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifa_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('role_code', models.IntegerField()),
                ('role_description', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='football.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
