# Generated by Django 6.0.4 on 2026-06-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_team_flag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='group_stage_close_processed',
            field=models.BooleanField(default=False),
        ),
    ]
