# Generated by Django 6.0.4 on 2026-07-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_season_group_stage_close_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='locked',
            field=models.BooleanField(default=False, help_text='Se marcado, nenhuma sincronização altera este jogo. Só edição manual no admin.'),
        ),
    ]
