# Generated by Django 6.0.1 on 2026-04-02 00:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football', '0006_official'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('requires_payment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pools_created', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='football.season')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoolBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score_pred', models.PositiveSmallIntegerField()),
                ('away_score_pred', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_bets', to='football.match')),
                ('winner_pred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_wins', to='football.team')),
            ],
            options={
                'ordering': ['match__match_date_brasilia', 'match__match_number'],
            },
        ),
        migrations.CreateModel(
            name='PoolBetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('exact_score', models.BooleanField(default=False)),
                ('winner_or_draw', models.BooleanField(default=False)),
                ('winner_advancing', models.BooleanField(default=False)),
                ('one_team_score', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='pool.poolbet')),
            ],
        ),
        migrations.CreateModel(
            name='PoolParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_points', models.IntegerField(default=0)),
                ('group_points', models.IntegerField(default=0)),
                ('knockout_points', models.IntegerField(default=0)),
                ('exact_score_hits', models.IntegerField(default=0)),
                ('winner_or_draw_hits', models.IntegerField(default=0)),
                ('champion_hit', models.BooleanField(default=False)),
                ('top_scorer_hit', models.BooleanField(default=False)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pool.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', 'joined_at'],
                'unique_together': {('pool', 'user')},
            },
        ),
        migrations.AddField(
            model_name='poolbet',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='pool.poolparticipant'),
        ),
        migrations.CreateModel(
            name='PoolLockWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('GROUP', 'Fase de grupos'), ('KNOCKOUT', 'Mata-mata')], max_length=20)),
                ('lock_at', models.DateTimeField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_windows', to='pool.pool')),
            ],
            options={
                'ordering': ['phase'],
                'unique_together': {('pool', 'phase')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='poolbet',
            unique_together={('participant', 'match')},
        ),
    ]
