# Generated by Django 6.0.1 on 2026-04-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_poolparticipantthirdplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolbet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poolbet',
            name='away_score_pred',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poolbet',
            name='home_score_pred',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
