# Generated by Django 6.0.1 on 2026-04-08 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_assignthird'),
        ('pool', '0005_poolprojectionrecalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolparticipant',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poolparticipant',
            name='champion_pred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_champion_predictions', to='football.team'),
        ),
        migrations.AddField(
            model_name='poolparticipant',
            name='runner_up_pred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_runner_up_predictions', to='football.team'),
        ),
        migrations.AddField(
            model_name='poolparticipant',
            name='third_place_pred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_third_place_predictions', to='football.team'),
        ),
        migrations.AddField(
            model_name='poolparticipant',
            name='top_scorer_pred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_top_scorer_predictions', to='football.player'),
        ),
        migrations.CreateModel(
            name='PoolOfficialResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_champion_pools', to='football.team')),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_result', to='pool.pool')),
                ('runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_runner_up_pools', to='football.team')),
                ('third_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_third_place_pools', to='football.team')),
                ('top_scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_top_scorer_pools', to='football.player')),
            ],
            options={
                'verbose_name': 'Resultado oficial do bolao',
                'verbose_name_plural': 'Resultados oficiais do bolao',
            },
        ),
        migrations.CreateModel(
            name='PoolScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_winner_or_draw_points', models.PositiveSmallIntegerField(default=6)),
                ('group_exact_score_points', models.PositiveSmallIntegerField(default=10)),
                ('group_one_team_score_points', models.PositiveSmallIntegerField(default=2)),
                ('knockout_winner_advancing_points', models.PositiveSmallIntegerField(default=8)),
                ('knockout_exact_score_points', models.PositiveSmallIntegerField(default=6)),
                ('knockout_one_team_score_points', models.PositiveSmallIntegerField(default=2)),
                ('bonus_champion_points', models.PositiveSmallIntegerField(default=50)),
                ('bonus_runner_up_points', models.PositiveSmallIntegerField(default=30)),
                ('bonus_third_place_points', models.PositiveSmallIntegerField(default=20)),
                ('bonus_top_scorer_points', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_config', to='pool.pool')),
            ],
            options={
                'verbose_name': 'Configuracao de pontuacao',
                'verbose_name_plural': 'Configuracoes de pontuacao',
            },
        ),
    ]
