# Generated by Django 6.0.1 on 2026-04-10 00:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_alter_poolscoringconfig_group_exact_score_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='first_place_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pool',
            name='first_place_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='pool',
            name='second_place_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pool',
            name='second_place_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='pool',
            name='third_place_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pool',
            name='third_place_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='pool',
            name='total_prize_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
