# Generated by Django 6.0.1 on 2026-04-10 12:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool", "0008_pool_first_place_amount_pool_first_place_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="admin_fee_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="pool",
            name="admin_fee_percentage",
            field=models.DecimalField(decimal_places=2, default=Decimal("5.00"), max_digits=5),
        ),
    ]
