# Generated by Django 6.0.1 on 2026-04-14 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_team_flag_image'),
        ('pool', '0009_pool_admin_fee_amount_pool_admin_fee_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='poolparticipant',
            index=models.Index(fields=['-total_points', 'joined_at'], name='pool_part_rank_idx'),
        ),
    ]
