# Generated by Django 6.0.1 on 2026-04-14 21:00

from decimal import Decimal

from django.db import migrations, models


def convert_legacy_round_split(apps, schema_editor):
    Pool = apps.get_model("pool", "Pool")
    Pool.objects.filter(
        admin_fee_percentage=Decimal("5.00"),
        first_place_percentage=Decimal("70.00"),
        second_place_percentage=Decimal("20.00"),
        third_place_percentage=Decimal("10.00"),
    ).update(first_place_percentage=Decimal("65.00"))


class Migration(migrations.Migration):

    dependencies = [
        ("pool", "0010_poolparticipant_pool_part_rank_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="first_place_percentage",
            field=models.DecimalField(decimal_places=2, default=Decimal("65.00"), max_digits=5),
        ),
        migrations.RunPython(convert_legacy_round_split, migrations.RunPython.noop),
    ]
