# Generated by Django 6.0.4 on 2026-05-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0011_adjust_pool_prize_percentage_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='show_supporter_stars',
            field=models.BooleanField(default=True),
        ),
    ]
