# Generated by Django 6.0.4 on 2026-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0013_redesign_scoring_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolscoringconfig',
            name='knockout_advancing_and_diff',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='poolscoringconfig',
            name='knockout_advancing_only',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
