# Generated by Django 6.0.4 on 2026-05-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0014_update_scoring_config_diff_and_advancing_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='pool_type',
            field=models.IntegerField(choices=[(1, 'Tipo 1 — Classificados travados, placar livre'), (2, 'Tipo 2 — Palpite progressivo')], default=1),
        ),
        migrations.AddField(
            model_name='poolbetscore',
            name='team_advancement_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poolparticipant',
            name='qualifier_bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poolscoringconfig',
            name='group_qualifier_points',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='poolscoringconfig',
            name='group_qualifier_position_bonus',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='poolscoringconfig',
            name='knockout_team_advancement_bonus',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
