# Generated by Django 6.0.4 on 2026-06-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0016_poolscoringconfig_knockout_draw_prediction_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolKnockoutPhaseScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_key', models.CharField(choices=[('R32', '32 Avos'), ('R16', 'Oitavas'), ('QF', 'Quartas'), ('SF', 'Semifinal'), ('FINAL', 'Final'), ('THIRD', 'Disputa de 3o lugar')], max_length=5)),
                ('exact', models.PositiveSmallIntegerField(default=40)),
                ('advancing_goals', models.PositiveSmallIntegerField(default=30)),
                ('diff', models.PositiveSmallIntegerField(default=25)),
                ('loser_goals', models.PositiveSmallIntegerField(default=22)),
                ('advancing_only', models.PositiveSmallIntegerField(default=20)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_phases', to='pool.poolscoringconfig')),
            ],
            options={
                'verbose_name': 'Faixa de mata-mata por fase',
                'verbose_name_plural': 'Faixas de mata-mata por fase',
                'unique_together': {('config', 'phase_key')},
            },
        ),
    ]
