# Generated by Django 6.0.4 on 2026-06-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0018_seed_knockout_phase_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolknockoutphasescoring',
            name='advancing_goals',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='poolknockoutphasescoring',
            name='advancing_only',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='poolknockoutphasescoring',
            name='diff',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='poolknockoutphasescoring',
            name='exact',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='poolknockoutphasescoring',
            name='loser_goals',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
