# Generated by Django 6.0.1 on 2026-04-02 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_tokens', to='pool.pool'),
        ),
    ]
