# Generated by Django 6.0.1 on 2026-01-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitetoken',
            name='bolao_name',
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='max_uses',
            field=models.IntegerField(default=10, help_text='Número máximo de usos (0 = ilimitado)'),
        ),
    ]
