# Generated by Django 6.0.1 on 2026-04-09 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitetoken_pool'),
        ('football', '0007_assignthird'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='world_cup_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporter_profiles', to='football.team'),
        ),
    ]
