# Generated by Django 6.0.4 on 2026-06-16 16:46

import src.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_is_supporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=src.accounts.models.profile_image_upload_to, validators=[src.accounts.models._validate_profile_image]),
        ),
    ]
