# Generated by Django 6.0.1 on 2026-03-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knockoutslot',
            name='group',
        ),
        migrations.RemoveField(
            model_name='knockout',
            name='match',
        ),
        migrations.RemoveField(
            model_name='knockoutslot',
            name='knockout',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='GroupEntry',
        ),
        migrations.DeleteModel(
            name='GroupStage',
        ),
        migrations.DeleteModel(
            name='Knockout',
        ),
        migrations.DeleteModel(
            name='KnockoutSlot',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
